import Navbar from "@/components/Navbar";
import Container from "@/components/Container";

import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Translatr</title>
      </head>
      <body>
        <Navbar />
        <div className="min-h-screen bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100">
          <Container>
            <main className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {children}
            </main>
          </Container>
        </div>
      </body>
    </html>
  );
}
